### ISSUE TITLE
If clustering is enabled, new created points are only visible after zoom

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender-digitizer#19]
Example: POI editing (from the documentation samples) with enabled clustering.

If I use the below configuration the following issue is reproducable:

- Create a new point
- Insert the mandatory values
- Save
- The point is not visible
- Zoom in/out: The point is visible.

If I turn of the clustering (by removing the below configuration), the point is directly visible after creation.

```yaml
clustering:
    -
      scale: 10000
      distance: 60
    -
      scale: 2500
      distance: 40
    -
      scale: 1000
      distance: 20
    -
      scale: 500
      distance: 1
      disable: true
```
