### ISSUE TITLE
Cluster Settings zoom out and lock

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender-digitizer#49]
The cluster settings create errors even if a clustering is not customized. Tested with Digitizer (pre) 1.2.

Steps to reproduce:

- The YAML below goes to the POI data.
- Customize the Digitizer (release/1.2 branch) with this configuration
- Load your map (default Bonn/Mapbender Users application)
- Zoom out to the last zoom-level.

Error Message in console:

```
Uncaught TypeError: Cannot read property 'activate' of undefined
    at Object.<anonymous> (js:35015)
    at Function.each (jquery.min.js:2)
    at t.(anonymous function).(anonymous function).updateClusterStrategies (http://localhost/mapbender/application/Funktionstest/assets/js:34975:15)
    at t.(anonymous function).(anonymous function).updateClusterStrategies (http://localhost/mapbender/components/jquery-ui/jquery-ui.min.js:6:4499)
    at t.(anonymous function).(anonymous function).<anonymous> (http://localhost/mapbender/application/Funktionstest/assets/js:34028:24)
    at initialize.triggerEvent (js:5592)
    at initialize.moveTo (js:5645)
    at initialize.done (js:5650)
    at initialize.stop (js:5604)
    at initialize.setCenter (js:5638)
```

Occurs at:
```
if(clusterSettings) {

                    if(clusterSettings.hasOwnProperty('disable') && clusterSettings.disable) {
                        schema.clusterStrategy.distance = -1;
                        var features = schema.layer.features;
                        widget.reloadFeatures(schema.layer, []);
                        schema.clusterStrategy.deactivate();
                        //schema.layer.redraw();
                        schema.isClustered = false;
                        widget.reloadFeatures(schema.layer, features);

                    } else {
                        schema.clusterStrategy.activate();     <---------------------------------------------
```

**Problem:**

- The application locks.

**Background information**

As you can see I didn't define a cluster strategy. After zooming out to the last zoom-level, the clusterSettings are filled with values. Before that, they are null (what I expect them to be).

# Yaml-configuration to reproduce

``` yaml
poi:
  label: 'point digitizing'
  inlineSearch: true
  maxResults: 500
  minScale: 25000
  printable: true
  featureType:
    connection: gisdb
    table: poi
    uniqueId: gid
    geomType: point
    geomField: geom
    srid: 4326
    print:
      templates:
        -
          template: a4_portrait_official_feature_data_demo
          label: 'Demo with feature information print (portrait)'
  events:
    onBeforeSave: "$feature->setAttribute('user_name', $user->getUsername());\n$feature->setAttribute('modification_date', date('Y-m-d'));\n$feature->setAttribute('group_name', implode(',',$userRoles));\n"
  openFormAfterEdit: false
  zoomScaleDenominator: 500
  allowEditData: true
  allowDelete: true
  allowDigitize: true
  allowLocate: true
  allowChangeVisibility: true
  showVisibilityNavigation: true
  displayPermanent: false
  displayOnInactive: false
  allowCustomerStyle: false
  useContextMenu: false
  refreshLayersAfterFeatureSave:
    - 417
  toolset:
    -
      type: drawPoint
    -
      type: modifyFeature
    -
      type: moveFeature
  popup:
    title: 'point test suite'
    width: 500px
  searchType: all
  tableFields:
    gid:
      label: Nr.
      width: 20%
    name:
      label: Name
      width: 80%
  styles:
    default:
      strokeWidth: 2
      strokeColor: '#0e6a9e'
      fillColor: '#1289CD'
      fillOpacity: 1
      fillWidth: 2
      pointRadius: 10
    select:
      strokeWidth: 3
      strokeColor: '#0e6a9e'
      fillOpacity: 0.7
      pointRadius: 10
  formItems:
    -
      type: tabs
      children:
        -
          type: form
          title: 'Basic information'
          css:
            padding: 10px
          children:
            -
              type: text
              title: 'Typ text'
              name: name
              css:
                width: 80%
              text: 'the name is:'
            -
              type: label
              title: 'Welcome to the digitize demo. Try the new Mapbender3 feature!'
            -
              type: input
              title: Name
              mandatory: true
              name: name
              mandatoryText: 'Please give a name to the poi.'
              infoText: 'Help: Please give a name to the new object.'
            -
              type: input
              title: Title
              mandatory: false
              name: title
              mandatoryText: 'Please give a title to the poi.'
            -
              type: textArea
              name: abstract
              title: Abstract
              placeholder: 'please edit this field'
            -
              type: select
              title: Type
              name: type
              multiple: true
              options:
                A: A
                B: B
                C: C
                D: D
                E: E
            -
              type: breakLine
        -
          type: form
          title: 'Personal information'
          css:
            padding: 10px
          children:
            -
              type: label
              title: 'Please give us some information about yourself.'
            -
              type: fieldSet
              children:
                -
                  type: input
                  title: Firstname
                  name: firstname
                  css: { width: 30% }
                -
                  type: input
                  title: Lastname
                  name: lastname
                  css: { width: 30% }
                -
                  type: input
                  title: E-Mail
                  name: email
                  css: { width: 40% }
                -
                  type: select
                  title: 'Wählen Sie einen Typ aus'
                  name: interests
                  single: true
                  separatator: ;
                  fieldType: array
                  options: { prof: Prof., dr: Dr., med: med., jur: jur., vet: vet., habil: habil }
                  css: { width: 80% }
            -
              type: date
              title: 'favorite Date'
              name: date_favorite
              placeholder: 'Please add a date in the following style dd-mm-yy.'
              dateFormat: dd-mm-yy
              value: 01-01-2016
              mandatory: true
              css:
                width: 25%
            -
              type: breakLine
            -
              type: breakLine
            -
              type: checkbox
              name: public
              value: true
              title: 'public (this new object is public)'
```
